### ISSUE TITLE
About activation

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#189] opened 2022-07-01 00:10 UTC
I put a shortcut for the Lizzieyzy jar file on my desktop and always launch it from there, but this way Lizzieyzy launches inactive.
In other words, in order to press the space key to stop the analysis, you need to activate Lizzieyzy by clicking the upper frame of Lizzieyzy once.
If you pin the exe file to the taskbar and launch it from there, it will launch in an active state.
However, it takes a bit of work to create the exe file, so I usually don't start it this way.
Normal Lizzie is started in the active state even if it is started from the shortcut of the jar file.
It's a trivial matter, but I think the Lizzie style is easier to use.

**Comment by yzyray** [comment] 2022-07-03 01:55
It should be fixed now,I have copied the wrong issue link in comment https://github.com/yzyray/lizzieyzy/commit/114347e6a18ee366779e2436f3505b414d00efa9 is for https://github.com/yzyray/lizzieyzy/issues/188...

**Comment by hope366** [comment] 2022-07-03 02:20
Thank you for your support.
I was able to confirm that the subboard was fixed.
But the activation is the same as before, it doesn't activate at boot time. Is it a Windows configuration issue? I'm going to ask someone else to try the Lizzieyzy I just compiled and see if it's a problem only for my PC environment.

**Comment by yzyray** [comment] 2022-07-03 02:32
What is your startup option about engine?
![image](https://user-images.githubusercontent.com/49384584/177022171-bcc76948-7acc-45eb-9222-3c1fd96a9f00.png)

**Comment by hope366** [comment] 2022-07-03 02:35
It looks like this.
![無題](https://user-images.githubusercontent.com/63999713/177022237-38c2a49b-5220-4ced-bc89-28ba714fbc26.png)

**Comment by yzyray** [comment] 2022-07-03 03:20
I can reproduce the issue but can't reproduce after https://github.com/yzyray/lizzieyzy/commit/c2cf0e93aa50e95c3f65888b658aeaf5e3b6a1fd

**Comment by hope366** [comment] 2022-07-03 04:32
By double-clicking the following two files in the "2022-05-13-windows64" folder, Lizzieyzy will start in the activated state.
It was inactive before `c2cf0e9`, but after `c2cf0e9` it starts with activation.
* bat starter(only display abnormal).bat
* bat starter(only exe failed).bat

When starting by double-clicking the jar file and exe file, the situation where it is not started in the activated state remains unsolved as before ...

**Comment by hope366** [comment] 2022-07-03 05:45
I had multiple people other than me verify it. It seems that it can be started in the active state.
It seems likely that the cause is in my PC environment. Initializing Windows may solve the problem ...

**Comment by yzyray** [comment] 2022-07-03 07:00
exe is stand alone,not based on the jar file,so if you only updated the jar file,exe will still be old.
but open from any bat should be same as double-clicking the jar file...its quite confused for me.
by the way what is your java version,its mine:
![image](https://user-images.githubusercontent.com/49384584/177028881-1ef4c228-a615-45de-90d8-07eea2caee5d.png)

**Comment by hope366** [comment] 2022-07-03 07:13
>exe is stand alone,not based on the jar file,so if you only updated the jar file,exe will still be old.

Yes, so I created an exe file from a newly compiled jar file. However, even if you double-click the exe file, it will start in the back view.
The java version looks like this:
![無題](https://user-images.githubusercontent.com/63999713/177029247-cacfa94d-bd6c-4823-bf06-b57b48a0d970.png)

**Comment by yzyray** [comment] 2022-07-03 09:05
I may have found the basic issue,can you try after https://github.com/yzyray/lizzieyzy/commit/a90fca695105b72f55b23b1efd900c8caf1d8fcc

**Comment by hope366** [comment] 2022-07-03 10:12
With a90fca6, it now starts in front view!!
I heard that it is a basic problem, but is there anything to do with what went wrong due to the difference in the environment?

**Comment by yzyray** [comment] 2022-07-04 00:14
Its some popup menu,like 'Sync' or 'Share' in bottom toolbar,for getting the size of these menus(without size I can not put them into right position),I make it visible and then invisible immediately,the  procedure is very fast so we can not actually see these menus,but it still affect the activition of main frame,maybe get focus on popup menus and then lost it.
The first commit I have no idea why main frame will lost activition,just active it again,but maybe popup menu get focus after(this will still have the issue) or before(this is fine) the second activition in different environment.
The second commit I find the true reason and delay the popup menu visible/invisible procedure, not to affect main frame activition

**Comment by hope366** [comment] 2022-07-04 00:49
There was a change in the bottom toolbar in https://github.com/yzyray/lizzieyzy/commit/a90fca695105b72f55b23b1efd900c8caf1d8fcc. What does it have to do with mainframe activation? I was wondering, but somehow I understood it from your explanation.
This issue is very trivial and seems to be of little concern when using Lizzieyzy, but I am deeply grateful to you for your persistent and continuous efforts to resolve the issue.

**Closed** 2022-07-05 22:17 UTC

**Comment by hope366** [comment] 2022-07-05 23:16
Thank you so much.
