### ISSUE TITLE
About analysis speed 

### ISSUE THREAD

**Issue by hope366** [yzyray/lizzieyzy#8] opened 2021-10-29 04:18 UTC
Using katago_20211025_trt64.exe used in lizzieyzy, one is normal lizzie and the other is lizzieyzy2.4.5, the situation when the same phase diagram is analyzed is shown in the screenshot below. 
Both threads used are numSearchThreads = 16. 
Both analysis widths are analysisWideRootNoise = 0.04. 
The GPU is RTX 2060. 
In terms of analysis speed, regular lizzie is about 1.5 times faster than lizzieyzy. It seems that the difference is always maintained at this level. Also, although the blue points and the displayed candidate moves are similar, there are some differences. What is the reason for these differences? 

<img src="https://user-images.githubusercontent.com/63999713/139372854-062067b9-6ac7-485e-a471-0c736ad49771.png" width="80%">
<img src="https://user-images.githubusercontent.com/63999713/139373127-2ffeb162-967d-4d37-ba34-5828efbf2671.png" width="80%">

**Comment by yzyray** [comment] 2021-10-30 02:41
I've update maven and jdk,complied 4 jars.
-jdk1.8 means complied with jdk1.8
-jdk11 means complied with jdk11
-modify means a little code modify maybe effect sub process.
[lizzie-yzy2.4.5-shaded-jdk1.8.zip](https://github.com/yzyray/lizzieyzy/files/7445702/lizzie-yzy2.4.5-shaded-jdk1.8.zip)
[lizzie-yzy2.4.5-shaded-jdk11-modify.zip](https://github.com/yzyray/lizzieyzy/files/7445701/lizzie-yzy2.4.5-shaded-jdk11-modify.zip) 
[lizzie-yzy2.4.5-shaded-jdk1.8-modify.zip](https://github.com/yzyray/lizzieyzy/files/7445699/lizzie-yzy2.4.5-shaded-jdk1.8-modify.zip)
[lizzie-yzy2.4.5-shaded-jdk11.zip](https://github.com/yzyray/lizzieyzy/files/7445700/lizzie-yzy2.4.5-shaded-jdk11.zip)

**Comment by hope366** [comment] 2021-10-30 03:18
I have tried all four types of jar files and they look almost the same as existing jar files in terms of analysis speed.
I have noticed one thing. When lizzieyzy uses the pondering on state for about 10 seconds, the number of GPU clocks decreases from 1800MHz to 1200HZz. Pondaling is the same for 10 seconds in a row or intermittently for a total of 10 seconds. In short, the load on the GPU will automatically decrease after about 10 seconds have passed since the GPU is heavily loaded. The analysis speed will decrease accordingly. 
This is a feature common to all five jar files, including existing jar files. 
With normal lizzie (an improved version of lizzie that I usually use https://github.com/hope366/Lizzie-improvements/releases/tag/v3.0), the high load condition of 1800MHz continues forever.

**Comment by yzyray** [comment] 2021-10-30 03:33
Which maven and jdk do you use to generate jar files for https://github.com/hope366/Lizzie-improvements/releases/tag/v3.0

**Comment by hope366** [comment] 2021-10-30 03:47
maven is "apache-maven-3.6.3-bin".
For java, "jdk-14.0.1" and "jre1.8_271" exist in the Program Files folder.
Looking at the program list in the control panel, it looks like the following regarding java. maven is not in the program list. 
![program](https://user-images.githubusercontent.com/63999713/139519168-bbf1eec3-7180-48db-99a2-1fc32740fd6a.png)

**Comment by yzyray** [comment] 2021-10-30 03:56
try this,I packaged your code https://github.com/hope366/Lizzie-improvements
hope it also has the issue....then it's my environment problem...
[lizzie-0.7.3-shaded.zip](https://github.com/yzyray/lizzieyzy/files/7445765/lizzie-0.7.3-shaded.zip)

**Comment by hope366** [comment] 2021-10-30 04:04
I tried lizzie-0.7.3-shaded.zip.
The high load condition continues at all times in any situation.

**Comment by yzyray** [comment] 2021-10-30 04:44
Really confused,just try to reset all code about start engine process to same with official lizzie....hope it works
[test1.zip](https://github.com/yzyray/lizzieyzy/files/7445833/test1.zip)

**Comment by hope366** [comment] 2021-10-30 04:53
I tried test1.zip, but as before, the GPU clock suddenly dropped after a heavy load of about 10 seconds ... 
I asked people other than me to try this phenomenon, but it seems to be almost the same.
By the way, does your environment always have a high load on the GPU?

**Comment by yzyray** [comment] 2021-10-30 05:02
My GPU clock with offical lizzie or your lizzie or lizzieyzy is almost same....around 1050Mhz...but my gpu is onlu MX250...

**Comment by yzyray** [comment] 2021-10-30 05:10
Do you have any computer with 3060 laotop,I have a 3060 laptop GPU compuer,can try it tommorrow.

**Comment by hope366** [comment] 2021-10-30 05:28
I only have one machine with a 2060, so I'm reaching out to more people to verify this issue.

**Comment by yzyray** [comment] 2021-10-30 05:41
I'm also tring to get some lizzieyzy users to try official lizzie.

**Comment by yzyray** [comment] 2021-10-30 09:12
I've asked 4 lizzieyzy users,with 2060,2060s,2080,3060.None of them have occured gpu clock dropped  after few seconds.
I can hardly find out the probem now,but I want to try simply start katago engine process.
test2 will start a engine process with out get any output stream,due to no output need manual press space after you think engine is loaded.
test3  will start a engine process with out get any input/output stream,and bunlded with a tensorrt exe file can auto analyze after loaded. 
[test2.zip](https://github.com/yzyray/lizzieyzy/files/7446146/test2.zip)
[test3.zip](https://github.com/yzyray/lizzieyzy/files/7446145/test3.zip)

**Comment by hope366** [comment] 2021-10-30 10:11
In test2, when I start lizzieyzy, no candidate is displayed on the board, but if I hold down the space key, it puts a load on the GPU, and it seems that analysis work is being done internally. However, the number of GPU clocks was 1865MHz only for the first 10 seconds, then 1365MHz was maintained for about 10 seconds, and then there was no load. And I couldn't close lizzieyzy and ended up closing it from the task manager. 

For test3 and katago_tensorRT.exe, the space key cannot be used to switch the analysis on and off, and the analysis is automatically continued. However, as for the analysis speed, it remains in a high load state for the first 10 seconds and after that, the load became low. 

By the way, I also verified katago 1.9.1 opencl and leelazero 0.17. The result is exactly the same as katago1.10.0, with normal lizzie forever under heavy load, but with lizzieyzy only the first 10 seconds or so under heavy load.
I haven't collected the verification results of many people yet, so there may be a problem with my environment.

**Comment by yzyray** [comment] 2021-10-30 10:20
I have recieved same issue report several monthes ago one time,that wa a machine with four GPUs and one GPU one behave like yours,can not solve either.I thought it was multi GPUs issue.but now I think it should be some strange bug with lizzieyzy.

**Comment by hope366** [comment] 2021-10-30 10:47
Katago's process priority remained "normal" both under heavy load and when the clock count dropped.
The antivirus software uses Avast. 
![無題](https://user-images.githubusercontent.com/63999713/139529737-9a5331ce-ef98-45b2-8c3e-4f8f8faf6a46.png)

**Comment by hope366** [comment] 2021-10-30 11:04
Compiled lizzieyzy-process.
It seemed to fail with a lot of errors, but lizzie-0.7.4-shaded.jar was generated.
lizzie-0.7.4-shaded.jar will continue to be heavily loaded on the GPU. In other words, the problem so far has been solved. However, the GUI design is that of regular lizzie, not lizzieyzy.

**Comment by yzyray** [comment] 2021-10-30 11:10
GUI should still looks like lizzieyzy,I have updated process bracn again,more clean up with maven.

**Comment by hope366** [comment] 2021-10-30 11:22
There seems to be a problem with my compilation method.
As you say, it was compiled as a GUI for lizzieyzy. There were no errors at compile time.
However, using the generated lizzie-yzy2.4.5-shaded.jar still does not solve the problem of falling into a low load state after a high load state of about 10 seconds.

**Comment by yzyray** [comment] 2021-10-30 11:27
OK,then the reason must not compile environment.Can you try official lizzie 0.6 release.That is the point I forked lizzie and start modify.

**Comment by hope366** [comment] 2021-10-30 11:54
I tried lizzie0.6.
The high load on the GPU continued for a while after the analysis was turned on, but it seems that the load will be low in about 30 to 50 seconds. The change seems to occur when the GPU temperature reaches about 70 ° C. 
At the first startup, the load became low in about 20 seconds, but I think that the load became low in a short time because the temperature of the GPU had risen during the tuning work.

**Comment by yzyray** [comment] 2021-10-30 12:01
If the tempreture can be a reason,how about set lizzieyzy to simple mode  by menu->view->simple mode. Default lizzieyzy takes more cpu resources than normal lizzie,simple mode won't.

**Comment by hope366** [comment] 2021-10-30 12:12
I also tried the official lizzie0.7. In this one, the GPU remains under high load all the time even when the GPU temperature exceeds 70℃. Probably, when they moved from 0.6 to 0.7, they changed the specification to focus on performance rather than GPU load.

I tried the simple mode, but the phenomenon that the clock number decreased after about 10 seconds did not change.
Incidentally, when the GPU temperature reaches around 70℃, the clock number decreases only for lizzie0.6, not for lizzieyzy, and after 10 seconds of using the high load state, regardless of the GPU temperature, it becomes the low load state.

**Comment by hope366** [comment] 2021-10-30 12:17
>How about make a bat file,and put engine command in the bat file,use bat in lizzieyzy.

I already have a file called "bat启动器(exe无法打开时使用).bat" in lizzieyzy. Is it possible to make it generic by just renaming the jar file in this file?

**Comment by yzyray** [comment] 2021-10-30 12:24
I mean put engine command in bat like 'katago gtp
 -model....' ,And use the bat like an engine

**Comment by hope366** [comment] 2021-10-30 12:32
I'm sorry, but I don't know how to use the engine command in a bat file. I would appreciate it if you could tell me if you like ...

**Comment by yzyray** [comment] 2021-10-30 12:47
I'm using cellphone currently,can't give command directly.but its not complicate,copy the exsit bat file you mentioned before,open with notepad,replace the line with the command you used in lizzieyzy's engine.and use the copied bat file like a engine exe but don't need to add parameters any more.

**Comment by hope366** [comment] 2021-10-30 13:05
`"command": "\"katago_tensorRT\\katago_yzy.exe\" gtp -model \"weights\\kata1-b40c256-s10150379520-d2474366098.bin.gz\" -config \"katago_configs\\default_gtp.cfg\"",`
I pasted the above part of config.txt into Notepad and saved it as a bat file, but it doesn't seem to start properly.
I am sorry for any inconvenience caused by my inexperience with computer programming.

**Comment by yzyray** [comment] 2021-10-30 13:13
You can find the right command through GUI,menu-settings-engines
![Screenshot_20211030_211222_youqu android todesk](https://user-images.githubusercontent.com/49384584/139534127-56a76998-970e-4fee-919b-73de800026b6.jpg)

**Comment by hope366** [comment] 2021-10-30 13:23
When I created a bat file that way and double-clicked it, the command prompt started. And it seems that it is stopped in the following state, is there any other work required? 
![無題](https://user-images.githubusercontent.com/63999713/139534401-0555c6cd-ddfc-463f-9e75-408e3365ce24.png)

**Comment by yzyray** [comment] 2021-10-30 13:37
Then use the bat file as katago engine in lizzieyzy.create a new engine by click add button in lizzieyzy Menu-settings-engine like previous,and click generate-other and select the bat file.
The new engine should work just like katago and does the GPU clock still dropped throw bat engine?
![Screenshot_20211030_213352_youqu android todesk](https://user-images.githubusercontent.com/49384584/139534796-9a34f264-5a67-4376-8454-0a4a716a1e10.jpg)

**Comment by hope366** [comment] 2021-10-30 13:48
Well, once you remember it was very easy.
I tried to start it immediately, but as usual, the number of GPU clocks drops after about 10 seconds have passed.

**Comment by yzyray** [comment] 2021-10-30 13:54
Not suprised.....thank you for all this tring.let me compare my code with official lizzie carefully.If I can find some possiable difference or make progress,I will
 comment again.

**Comment by hope366** [comment] 2021-10-30 13:59
Thank you very much for your active efforts to solve the problem.

**Comment by yzyray** [comment] 2021-10-31 04:16
I've restored my code about start engine part to same as official lizzie in process branch, and I have a new thought if it is lizzieyzy GUI part make GPU clock drop,even not load any engine.Can you try to run your lizzie with engine analyzing and lizzieyzy without any engine loaded,or run both lizzie and lizzieyzy with engine analyzing.

**Comment by hope366** [comment] 2021-10-31 04:30
>Can you try to run your lizzie with engine analyzing and lizzieyzy without any engine loaded,or run both lizzie and lizzieyzy with engine analyzing

I am an amateur when it comes to computer programming, so I can't do that.
However, if it is not too difficult and can be done with a little advice, I am willing to try.

**Comment by yzyray** [comment] 2021-10-31 04:38
![image](https://user-images.githubusercontent.com/49384584/139567860-4526d92f-695d-4bc3-8880-9a8732b9e1a9.png)
Lizzieyzy allow run without engine loaded,and if I record correctly official lizzie also can do it by set first engine command empty.And both runing is simply open-load engine and start analyzing.See if the GPU clock drops in this two situations,

**Comment by hope366** [comment] 2021-10-31 04:51
In my environment, the GPU clock speed is usually 300MHz.
If you start lizzieyzy with an empty engine, it will be 1365MHz for a moment at startup, but it will be 300MHz all the time after that.
The regular lizzie also started with an empty engine, but it was the same as lizzieyzy in terms of GPU clock count.

**Comment by yzyray** [comment] 2021-10-31 04:57
If you leave lizzieyzy open with empty engine and start regular lizzie with engine analyzing,will GPU clock still be high load condition of 1800MHz continues forever?
If you start both lizzie and lizzieyzy with engine analyzing,what GPU clock is,and if press space to stop ponder in lizzie will lizzieyzy still behave like before,dorp gpu clock after 10 seconds?

**Comment by hope366** [comment] 2021-10-31 05:01
I'm sorry, I forgot to test what the situation was like at the time of the analysis.
A normal lizzie seems to have a GPU clock that repeats 405MHz and 1365MHz forever every 2-3 seconds if you hold down the spacebar.
lizzieyzy seems to have a GPU clock that goes back and forth between 405MHz and 450MHz on an irregular basis when you hold down the spacebar.

**Comment by yzyray** [comment] 2021-10-31 05:06
No, I'm not mean to observe the GPU clock when lizzie/lizzieyzy start without engine.
I mean open lizzie and lizzieyzy at the same time,lizzie with engine analyzing and lizzieyzy without engine loaded.
And reverse it,lizzieyzy with engine analyzing and lizzie without engine loaded.
Or lizzieyzy with engine analyzing and lizzie with engine analyzing.

**Comment by hope366** [comment] 2021-10-31 05:34
First of all, I loaded the engine into both lizzies and booted them up; the GPU clock speed was initially 1800MHz, but it went down to 1200MHz in about 15 seconds. One thing I noticed is that the One thing I noticed, when I moved the mouse pointer on the normal lizzie board, the GPU clock speed went to 1800MHz for about 5 seconds.

Next, I started lizzieyzy without an engine and normal lizzie with an engine at the same time. The number of GPU clocks remained high forever. 

And finally, lizziyzy with an engine and regular lizzie without an engine. Surprisingly, the GPU clock remains high forever under these circumstances. In fact, the analysis speed of lizziyzy is about 1.5 times faster than when the number of clocks is low.

**Comment by yzyray** [comment] 2021-10-31 05:50
It sounds like regular lizzie can make GPU clock remains high forever,no matter the engine is started from lizzie or lizzieyzy.
> And finally, lizziyzy with an engine and regular lizzie without an engine. Surprisingly, the GPU clock remains high forever under these circumstances. In fact, the analysis speed of lizziyzy is about 1.5 times faster than when the number of clocks is low.
In this case,does your mouse pointer on lizzieyzy or regular lizzie?

**Comment by hope366** [comment] 2021-10-31 05:58
>In this case,does your mouse pointer on lizzieyzy or regular lizzie?

No matter where the mouse pointer is, the GPU clock number remains high and the analysis speed remains fast.
Even if the normal lizzie is hidden in the taskbar, as long as it is running, turning on the analysis in lizzieyzy will keep the GPU clock speed high.

**Comment by hope366** [comment] 2021-10-31 06:06
>In addition,when you use only lizzieyzy analyzing,afrer GPU clock dropped down,if you mouse over a candidate,or changed lizzieyzy's window size will GPU clock return to a high level for several seconds?

No, those operations did not change the number of GPU clocks. By the way, if you continue to resize the window, the CPU usage will increase from the usual 2 to 3% to about 30%.

**Comment by yzyray** [comment] 2021-10-31 06:30
Do you use Panel UI mode in lizzie?If so try not use it,can lizzie still remain high GPU clock?

**Comment by hope366** [comment] 2021-10-31 06:35
I usually use the panel UI mode.
So I changed to normal mode and observed it, but the GPU clock number remains high forever.

**Comment by yzyray** [comment] 2021-10-31 07:48
Still can not figure out the reason clearly ,but restore part code like regular lizzie.Try this....hope it can works.
[lizzie-test-shaded.zip](https://github.com/yzyray/lizzieyzy/files/7448309/lizzie-test-shaded.zip)

**Comment by hope366** [comment] 2021-10-31 08:08
I tried lizzie-test-shaded.zip.
I haven't done many experiments, but it looks like the following.
When using the TensorRT engine, the GPU clock count dropped in about 30 seconds.
When using the OpenCL engine, the GPU clock count dropped in about 60 seconds.

**Comment by yzyray** [comment] 2021-10-31 08:20
[lizzie-test2-shaded.zip](https://github.com/yzyray/lizzieyzy/files/7448349/lizzie-test2-shaded.zip)
Last attampt...or I dont think I can fix it unless there is a machine with the issue in my front....or  get other helps.

**Comment by hope366** [comment] 2021-10-31 08:32
I tried lizzie-test2-shaded.zip, but the result was almost the same as lizzie-test-shaded.zip in terms of GPU clock count ...

By the way, I don't think this has anything to do with the problem of the GPU clock slowing down, but let me tell you.
lizzie-test2-shaded.zip makes the drawing on the board look obviously dirty compared to the others. Next, as a feature common to both lizzie-test-shaded.zip and lizzie-test2-shaded.zip, the entire GUI is white for about 3 seconds immediately after startup. Then, the moment the engine load is completed, the board will be displayed and the analysis will start at the same time.
Normal lizzieyzy will show the board as soon as it starts.

**Comment by yzyray** [comment] 2021-10-31 08:39
I konw these small issues,I've delete lots of codes so some thing went wired.but as you said has nothing to do with GPU clock issue.I notice my GPU clock will never goes down,even just start windows,running nothing.I'm gonna update my GPU drivers to see if the clock can go down some times.By the way,which driver version are you using? Can you update drivers?maybe helps.

**Comment by hope366** [comment] 2021-10-31 08:49
I recently updated my graphics driver to 496.13. However, I just confirmed that the latest version, 496.49, was released on October 26th.
https://www.nvidia.co.jp/Download/driverResults.aspx/183462/jp
I will install this immediately.

**Comment by yzyray** [comment] 2021-10-31 08:55
I just update to  496.49 and my gpu clock can go down now,but still can not reproduce the issue.

**Comment by hope366** [comment] 2021-10-31 09:20
Updated to 496.49. The official lizziyzy 2.4.5 still drops the GPU clock in a few seconds, but lizzie-test2-shaded keeps the GPU clock high for about 2 minutes. And after that, it seems that the state where the number of clocks is high and the state where the number of clocks is low are repeated irregularly. 

I have noticed something else. The normal lizzie and lizzieyzy use the same engine and weight, but the sound heard from the computer is different when analysis is on.
You can't tell the difference in the OpenCL version, but the sound quality is clearly different in the TensorRT version. Both OpenCL versions feel quiet to the human ear, but the regular lizzie Tensor RT is close to this. And lizzieyzy's Tensor RT sounds a little loud. It feels more GPU-loaded.

**Comment by yzyray** [comment] 2021-10-31 11:52
Finally get this issue reproduced on my laptop,by disable the intergrated GPU use RTX3060 only.Although still dont know how to solve it,but must is close to solve it!

**Comment by hope366** [comment] 2021-10-31 12:07
That was good news.
I sincerely hope that the problem will be solved.

**Comment by yzyray** [comment] 2021-11-01 01:27
After tried many period codes of lizzie,I found on my laptop the last official release aslo have the issue,but yours and kaorahi's patched_0.7.4 is fine.I checked the difference,and this works on my laptop,hope it works on your machine too.
[test1101-1.zip](https://github.com/yzyray/lizzieyzy/files/7450216/test1101-1.zip)

**Comment by hope366** [comment] 2021-11-01 01:50
I tried test1101-1.zip. I haven't verified it for a long time, but it seems that there is no phenomenon that the clock number of GPU decreases so far!!
I've also tried the official lizzie 0.7.4, which in most cases doesn't reduce the GPU clock count, but seems to do so in rare cases.

I heard that there is no problem with my and kaorahi's patched_0.7.4, but what was the cause?

**Comment by yzyray** [comment] 2021-11-01 02:00
>I heard that there is no problem with my and kaorahi's patched_0.7.4, but what was the cause?

patched_0.7.4 also have these fix codes,I cant understand how it fix this strange bug....just try various version codes and find it!
Code is here:https://github.com/featurecat/lizzie/pull/783
Actually work part is:
>  public void addNotify() {
    // needless?
    // https://stackoverflow.com/questions/3435994/buffers-have-not-been-created-whilst-creating-buffers
    super.addNotify();
    createBufferStrategy(2);
  }

**Comment by hope366** [comment] 2021-11-01 02:34
It seems to be the code to fix a bug I happened to encounter while verifying https://github.com/featurecat/lizzie/issues?page=2&q=is%3Aissue+is%3Aopen.
I think there are many differences between me and kaorahi's lizzie from the official lizzie.
In a short amount of time from yesterday to today, I'm surprised that you've identified the areas that affect this bug fix.

**Comment by yzyray** [comment] 2021-11-01 02:34
By the way,I removed a integrated browser in the prevous test jar file,due to the file size limit.I will release a new version in few days if the issue is indeed solved.

**Comment by yzyray** [comment] 2021-11-01 02:58
I have almost removed ervery thing in lizzieyzy...then realized maybe it is not some bug codes in lizzieyzy,but some useful codes in lizzie-improvement...then a checked patched_0.7.4 and last official release...and then test all the pr involved a code changed about LizzieFrame.java still not merged in lizzie,fortunately find it without test too much pr.

**Comment by hope366** [comment] 2021-11-01 03:30
>fortunately find it without test too much pr.

That was good news. I'm glad to see that your proactive approach to the problem has paid off.
By the way, when I unzipped 20211027-windows64.rar, I heard from people around me that antivirus software warned me about the file "dm.dll" in the readboard folder. Is it safe?

**Comment by yzyray** [comment] 2021-11-01 03:43
It is a dll for sync board.Has some function of detect other program like foxweiqi,tygem.so the action maybe a little like virus but it is safe.If remove it will only make make this part of board sync tool unavailable.
![image](https://user-images.githubusercontent.com/49384584/139618783-a362ab4e-e0ca-4a77-8306-498b9005a0a2.png)

**Comment by hope366** [comment] 2021-11-01 03:56
I see. Thank you very much.
I'm still not sure what exactly the sync board feature is and how useful it is, but I recently discovered a feature that Fox kifu can easily reproduce and I think it's very useful.

**Comment by yzyray** [comment] 2021-11-01 06:38
Yes, synchronization other program's board into lizzieyzy is the main function of 'board Synchronization tools',And probably I can get rid of dm.dll in next release without destroy any synchronization function.

**Comment by hope366** [comment] 2021-11-01 07:22
That was good news. 
In addition to dm.dll...
* Installation of CPU version KataGo in addition to OpenCL and TensorRT 
* Compress to .zip instead of .rar. 
* Menu and other Japanese display 

I'm used to PCs and English notation to some extent, so I can use it as it is without much trouble, but many Go users in Japan are old and often have PCs with low specifications.
Therefore, I would like to inform you that the above requests have been raised.

**Comment by yzyray** [comment] 2021-11-01 09:05
OK,I can update zip verion packages and all-in-one package with cpu version KataGo,but I dont know Japanese ....and this is my first time attempt to modify a software,so many codes are messy,I think even a Japanese  is not easy to translate the menu and other stuff....

**Comment by hope366** [comment] 2021-11-01 09:28
Even though I am a beginner in computer programming, I can now translate normal lizzie into Japanese with just a few instructions. However, lizzieyzy has a lot of items, and I think the code is probably complicated, so I don't think it's easy to translate into Japanese. Chinese is a hassle to decipher, but English shouldn't be too difficult once you get used to it ... at least I think so.We hope that many Japanese users will become accustomed to English and master lizzieyzy. 
Anyway, I am very grateful to you for responding to my request so far.

**Comment by hope366** [comment] 2021-11-02 08:47
In a post a while back, I said that normal lizzie and lizzieyzy sound different from the PC when analysis is on, which was my mistake.
The sound was different because there was a difference in the value of each numSearchThreads.
In the improved version of lizzie, "16" is set based on the result of the benchmark test. I thought that lizzieyzy also set it to "16", but it seems that he forgot to change it to "16" when he upgraded from 2.4.4 to 2.4.5.
I'm sorry for making a misleading report.

**Comment by yzyray** [comment] 2021-11-02 14:34
Unfortunately ,I've found the bug have not been totally fixed,If a new dialog(like menu->file->open from online) or tips(like click menu->analze->auto analyze when no next move or delete a branch) is shown and which have not extends lizzieframe,after ten or more seconds,the GPU clock will decrese and even close the dialog/tips the GPU clock seems never return....It happens on all lizzie based jars,lizzie-imrovement/lizzieyzy/patched_0.7.4
Can you try if this will happen on your machine too?

**Comment by yzyray** [comment] 2021-11-02 14:55
I have a strange solution...start another jar which has only one JFrame with bug fix codes,and set it invisible.Then no matter how lizzie show tips dialogs..GPU clock never decreased.But it is much too lame....

**Comment by kaorahi** [comment] 2021-11-02 15:06
Do you mean that we need something like kaorahi/lizzie@93628753 for all dialogs?

**Comment by yzyray** [comment] 2021-11-02 15:40
> Do you mean that we need something like [kaorahi/lizzie@9362875](https://github.com/kaorahi/lizzie/commit/93628753) for all dialogs?

Yes,but for JDialogs,super(Lizzie.frame); will works,for JOptionPane,JOptionPane.showConfirmDialog( Lizzie.frame,
does not woks.

**Comment by yzyray** [comment] 2021-11-02 15:50
There is another solution,In my previous debug the decease has a premise which is continuously refresh lizzie.frame for a few seconds.
when parseing engine's output `info move ....` after get new candidates infos,it will refresh lizzie.frame once.
So a dialog/frame/JOptionPane with out bug fixs codes is shown and at same time the engine is pondering,after a few seconds GPU clock decresed.
Maybe another solution is when a new dialog/frame/JOptionPane is shown,we stop ponder automaticly.

**Comment by yzyray** [comment] 2021-11-02 16:10
I have only test not panel UI mode previously,just now I tested panel UI mode,GPU clock never decreased no matter which dialog/JOptionPane  is shown

**Comment by kaorahi** [comment] 2021-11-02 16:24
Only "normal UI" has `createBufferStrategy(2)`. What if you delete this line in `gui/LizzieFrame.java`?

**Comment by yzyray** [comment] 2021-11-02 17:18
The issue seems vary unstable,after reboot and without any other program,I have found panelUI will also make GPU clocck decreased...even without any dialogs and if remove `createBufferStrategy(2)` in lizzieframe for normal UI,it will behave like panel UI, GPU clock decreased without any dialogs.

**Comment by yzyray** [comment] 2021-11-02 17:24
I've found the condition of how to make panel UI trigger the issue.It is use view->simplify.
In default view panel UI doesnt have this issue,but in simpilfy it has.

**Comment by yzyray** [comment] 2021-11-02 17:33
Another clue is when I open a chrome based browser and start lizzie with `-Dsun.java2d.opengl=true` the GPU clock is low at start without wait a few seconds.
When I dont open browser the opton `-Dsun.java2d.opengl=true` will make lizzie maintain the gpu clock high forever with any dialogs with or without createBufferStrategy panel UI or normal UI.

**Comment by yzyray** [comment] 2021-11-02 17:46
I think the issue only affect the GPU used to diaplay lizzie,based on test on a laptop can change mode bettween one discrete GPU and two GPUs（the other one is integrate GPU）
And a bug reported long time ago,a machine with 4 GPUs,only first GPU clock is low when runing lizzieyzy.In other case such as runing katago through other GUI 4 GPUs clock is all high.

**Comment by kaorahi** [comment] 2021-11-02 17:56
Hmm... Does "analyze-update-interval-centisec" in config.txt affect the issue?

**Comment by hope366** [comment] 2021-11-02 18:13
I tried it with lizzie-improvement, but regardless of the type, when I displayed the dialog window anyway, the GPU clock number dropped about 15 seconds later.
"Analyze-update-interval-centisec" tried 1,20,50,100 etc., but it doesn't seem to be effective.

**Comment by yzyray** [comment] 2021-11-03 01:07
Yes,changed "Analyze-update-interval-centisec" does not help,even I set to 100,and I tested another lizzie-forked program [mylizzie](https://github.com/aerisnju/mylizzie),also have the issue.
![image](https://user-images.githubusercontent.com/49384584/139977410-d186b02b-4cfa-430f-a59d-882f9517f2f7.png)

**Comment by yzyray** [comment] 2021-11-03 01:49
I did a simple test,even with this simple code,the issue remains,just one java file:
frame.createBufferStrategy(2); Can solve the issue in this test,even with  shown JOptionPane  or JDialog.
> import java.io.BufferedInputStream;
> import java.io.BufferedOutputStream;
> import java.io.IOException;
> 
> import javax.swing.JDialog;
> import javax.swing.JFrame;
> import javax.swing.JOptionPane;
> 
> public class MainClass {
> 	  public static void main(String[] args) {
> 		  JFrame frame= new JFrame();
> 		  frame.setSize(200,200);		 
> 		  frame.setVisible(true);
> 		  frame.createBufferStrategy(2);	//with this line,the issue disappeared	  
> 		  String engineCommand="\"katago\\katago.exe\" gtp -model \"weights\\g170e-b15c192-s1672170752-d466197061.bin.gz\" -config \"katago\\default_gtp1.cfg\"";
> 		  try {
> 			Process process =Runtime.getRuntime()
> 			  .exec(engineCommand);
> 			
> 			Thread.sleep(3000);
> 
>             Runnable runnable2 =
>                 new Runnable() {
>                   public void run() {
>                 	  BufferedInputStream inputStream= new BufferedInputStream(process.getInputStream());
>                 	  try {
>                 	      int c;
>                 	      StringBuilder line = new StringBuilder();
>                 	      while ((c = inputStream.read()) != -1) {
>                 	        line.append((char) c);
>                 	        if ((c == '\n')) {
>                 	        	if (line.toString().startsWith("info")) {
>                 	        		frame.repaint();
>                 	        	}
>                 	          line = new StringBuilder();
>                 	        }
>                 	      }
>                 	    } catch (IOException e) {
>                 	      e.printStackTrace();
>                 	    }
>                   }
>                 };
>             Thread thread2 = new Thread(runnable2);
>             thread2.start();
> 			 
> 			sendCommand(new BufferedOutputStream(process.getOutputStream()),"kata-analyze 10");
> 			JOptionPane.showMessageDialog(
> 					  null,
> 		                "test"); //show JOptionPane will not decrease GPU clock in this simple code test
> 			  JDialog dialog= new JDialog();
> 			  dialog.setSize(200,200);		 
> 			  dialog.setVisible(true); //show dialog will not decrease GPU clock in this simple code test
> 		  } catch (Exception e) { //with this line,the issue disappeared
> 			// TODO Auto-generated catch block
> 			e.printStackTrace();
> 		}
> 	  }
> 	  
> 	  private static void sendCommand (BufferedOutputStream stream,String command) throws IOException {
> 		  stream.write((command + "\n").getBytes());
> 		  stream.flush();
> 	  }
> }
>

**Comment by kaorahi** [comment] 2021-11-03 09:57
You captured a great hint that looks strange. `createBufferStrategy(2)` does nothing except for waste of some resources in both patched_0.7.4 and your test code, I suspect. Right? (We have no `getBufferStrategy()`.)

**Comment by kaorahi** [comment] 2021-11-03 14:42
Your test code seems to call `JOptionPane.showMessageDialog`, `frame.repaint`, etc. outside EDT. Is this ok? Should we use `SwingUtilities.invokeLater`?

**Comment by hope366** [comment] 2021-11-03 18:18
When the dialog window is displayed with "Normal UI" or "View-> Simplify Mode of the panel UI", the number of clocks decreases in 10 seconds or so, but move the mouse cursor around the check box in the dialog window Continuing, the number of clocks seems to remain high.

**Comment by yzyray** [comment] 2021-11-04 01:12
> Your test code seems to call `JOptionPane.showMessageDialog`, `frame.repaint`, etc. outside EDT. Is this ok? Should we use `SwingUtilities.invokeLater` like [featurecat/lizzie#782](https://github.com/featurecat/lizzie/pull/782)?
I changed code to use SwingUtilities.invokeLater,all issue remains.
<details>
  <summary>Code</summary>
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.IOException;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class MainClass {
	  public static void main(String[] args) {
		  JFrame frame= new JFrame();
		  frame.setSize(200,200);		 
		  frame.setVisible(true);
		  frame.createBufferStrategy(2);		  
		  String engineCommand="\"katago\\katago.exe\" gtp -model \"weights\\g170e-b15c192-s1672170752-d466197061.bin.gz\" -config \"katago\\default_gtp1.cfg\"";
		  try {
			Process process =Runtime.getRuntime()
			  .exec(engineCommand);
			
			Thread.sleep(3000);

            Runnable runnable =
                new Runnable() {
                  public void run() {
                	  BufferedInputStream inputStream= new BufferedInputStream(process.getInputStream());
                	  try {
                	      int c;
                	      StringBuilder line = new StringBuilder();
                	      while ((c = inputStream.read()) != -1) {
                	        line.append((char) c);
                	        if ((c == '\n')) {
                	        	if (line.toString().startsWith("info")) {
                	        		SwingUtilities.invokeLater(
                	        		        new Runnable() {
                	        		          public void run() {
                	        		        	  frame.repaint();
                	        		          }
                	        		        });                	        		
                	        	}
                	          line = new StringBuilder();
                	        }
                	      }
                	    } catch (IOException e) {
                	      e.printStackTrace();
                	    }
                  }
                };
            Thread thread = new Thread(runnable);
            thread.start();
      		sendCommand(new BufferedOutputStream(process.getOutputStream()),"kata-analyze 10");
        	SwingUtilities.invokeLater(
    		        new Runnable() {
    		          public void run() {    		      
    		    			JOptionPane.showMessageDialog(
    		    					  null,
    		    		                "test");
    		    			  JDialog dialog= new JDialog();
    		    			  dialog.setSize(200,200);		 
    		    			  dialog.setVisible(true);
    		          }
    		        });		
		  } catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	  }
	  
	  private static void sendCommand (BufferedOutputStream stream,String command) throws IOException {
		  stream.write((command + "\n").getBytes());
		  stream.flush();
	  }
}
</details>


> You captured a great hint that looks strange. `createBufferStrategy(2)` does nothing except for waste of some resources in both patched_0.7.4 and your test code, I suspect. Right? (We have no `getBufferStrategy()`.)

Yes,We have no `getBufferStrategy()` but there may have some deep level issue to do with hardware acceleration opengl or something(just guessing,I dont have any knowlage about this)...so without the `createBufferStrategy(2)` GPU clock decreased.Currently  `createBufferStrategy(2)` is the only code could help maintain GPU clock...

**Comment by yzyray** [comment] 2021-11-04 01:27
I tested another my machine,does not have the issue at all with all kinds of lizzie based jars.
I also have found a lizzieyzy user with this issue.
Here is the list of some system or hardware info of three machines:
1.my laptop with the issue: one GPU:RTX3060 laptop drivers 496.49   windows10(10.0.18363)
2.my machine without the issue: one GPU:GTX 1060 drivers 425.25   windows10(10.0.14393)
3.a lizzieyzy user with this issue: one GPU:GTX 1050ti windows10 (I have remote controled the machine but have not ware of getting more infomation...) 
Maybe operating system or GPU drivers have something to do with the issue,and GPU generation may not affect.I have some trouble to update GPU driver on old system windows10(10.0.14393),and dont have enough time to reinstall system for the machine....

**Comment by hope366** [comment] 2021-11-04 01:49
I will also give you information about my environment.
GPU: RTX2060 desktop drivers 496.49 windows10 ver.21H1 (OS build 19043.1288)

**Comment by yzyray** [comment] 2021-11-05 02:42
I have noticed,when lizzie caused GPU clock dropped,even start a new katago engine in independent command window and pondering with 'kata-analyze' or 'genmove' the GPU clock is still low.

**Comment by yzyray** [comment] 2021-11-06 04:31
Tried some -Dsun.java2d parameters....does not works at all
I'll give up debug and choose the 'lame' solution:
Start another jvm and run a empty frame with code `createBufferStrategy(2)` in tha jvm to keep GPU clock high.

**Closed** 2021-12-28 14:36 UTC
